[project]
name = "envsync"
version = "0.1.0"
description = "Simple env switcher"
dependencies = ["typer"]

[project.scripts]
envsync = "envsync.main:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
